# Use SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy project files
COPY *.csproj ./
RUN dotnet restore

# Copy all files
COPY . ./
RUN dotnet publish -c Release -o /app/publish

# Use runtime image to run the app
FROM mcr.microsoft.com/dotnet/runtime:8.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

# Command to run console app
ENTRYPOINT ["dotnet", "YourConsoleApp.dll"]
